import { auth } from '@/auth'
import { TooltipProvider } from '@/components/ui/tooltip'
import AppProvider from '@/provider/AppProvider'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Raleway } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'sonner'
import './globals.css'

const raleway = Raleway({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Musa Gala - Admin Dashboard',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className={`${raleway.className} antialiased`}>
        <AppProvider>
          {' '}
          {/* This should be here */}
          <SessionProvider session={session}>
            <TooltipProvider>{children}</TooltipProvider>
          </SessionProvider>
        </AppProvider>
        <Toaster richColors position="bottom-right" />
        <NextTopLoader showSpinner={false} color="#1E2A38" />
      </body>
    </html>
  )
}
