import { auth } from '@/auth'
import { TooltipProvider } from '@/components/ui/tooltip'
import AppProvider from '@/provider/AppProvider'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import NextTopLoader from 'nextjs-toploader'
import { Toaster } from 'sonner'
import './globals.css'

export const metadata: Metadata = {
  title: 'Musa Gala - Admin Dashboard',
  description: 'Generated by create next app',
  icons: {
    icon: 'https://files.edgestore.dev/2pgl62wxp0dbg019/Dev/_public/c07daf32-7d8a-4490-994e-00f3431e3de4.png',
  },
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await auth()
  return (
    <html suppressHydrationWarning={true} lang="en">
      <body className="antialiased font-sans">
        <AppProvider>
          {' '}
          {/* This should be here */}
          <SessionProvider session={session}>
            <TooltipProvider>{children}</TooltipProvider>
          </SessionProvider>
        </AppProvider>
        <Toaster richColors position="bottom-right" />
        <NextTopLoader showSpinner={false} color="#1E2A38" />
      </body>
    </html>
  )
}
